
<div class="header-bg">
    <div class="header-title">AGENT DASHBOARD</div>
</div>
<div class="side-menu show-for-small-only">
    <ul>
        <li class="active curr-chat"><a href="<?= $this->url('agent') ?>" title="">Current Chats</a></li>
    </ul>
</div>
<div class="main-content">           
    <form class="text-right">
        <div>
            <div class="inline-block switch-text">Available for Chats :</div>
            <div class="switch tiny round inline-block m-0 v-middle">
                <input class="switch-input m-0" id="Switch" type="checkbox" name="Switch" checked>
                <label class="switch-paddle" for="Switch">
                    <span class="show-for-sr">Available for Chats</span>
                </label>
            </div>
        </div>
    </form>
    <?php //if(count($data) != 0){
//            print_r($data);
        ?>
    <div class="text-center">
        <ul class="tabs" data-tabs id="agent-chat-tabs">
            <li class="tabs-title is-active"><a href="#panel1" aria-selected="true">Chat 1</a></li>
            <li class="tabs-title"><a href="#panel2">Chat 2</a></li>
            <li class="tabs-title"><a href="#panel3">Chat 3</a></li>
            <li class="tabs-title"><a href="#panel4">Queue</a></li>
        </ul>
    </div>
    <div class="tabs-content agent-chat-tabs" data-tabs-content="agent-chat-tabs">
        
        <div class="tabs-panel is-active" id="panel1">
            <div class="tab-agent-detail">
                <div class="tab-agent-header">
                    <div class="large-6 columns">
                        <div><span>Customer Name</span> :  James</div>
                        <div><span>Customer Email</span> :  Not Entered</div>
                        <div><span>Page on Site</span> :  http://www.companypage.com/pagecustomeronwhenchatinitiated/...</div>
                    </div>
                    <div class="large-6 columns">
                        <div>Initiated Chat (or reply to proactive chat)</div>
                        <div>Customer is using SMS (vs Chat on Site, or Chat on Mobile Site?</div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="tab-agent-content">
                    <div class="tab-agent-comment">
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">Hello, I need help with XYZ</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">
                                I will be happy to help you with XYZ, What is your questions?
                            </div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">
                                I’d like to know the dimensions, so it will fit
                            </div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">How can I help you?</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only  l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">I whould like to ask you questions.</div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="tab-agent-footer all-chats-box columns">
                    <div class="large-12 columns p-0">
                        <div class="large-10 medium-9 small-12 columns">
                            <form class="tab-agent-input large-12 small-12 v-middle m-r-10">
                                <input type="text" class="form-control">                                        
                            </form>
                            <a href="#" title="" class="form-que-img">
                                <img src="<?= $this->basePath(); ?>/images/question-icon.png">
                            </a>
                        </div>
                        <div class="large-2 medium-3 small-12 text-right p-0 small-m-t-10 columns">
                            <a class="button small radius m-r-10">SEND</a>
                            <a href="javascript:void(0)" class="transfer-chat-btn inline-block">
                                <img src="<?= $this->basePath(); ?>/images/pop-up-open.png" alt="" title="">
                            </a>
                        </div>
                        <div id="transfer-chat" class="transfer-chat-box"  style="display:none;">
                            <div class="large-12 columns transfer-title">
                                <input type="text" class="form-control" value="" placeholder="Enter Name"> 
                            </div>
                            <div class="large-12 columns transfer-btn">
                                <a href="#" title="Transfer Chat" class="button small radius">Transfer Chat</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="tabs-panel" id="panel2">
            <div class="tab-agent-detail">
                <div class="tab-agent-header">
                    <div class="large-6 columns">
                        <div><span>Customer Name</span> :  Andrew</div>
                        <div><span>Customer Email</span> :  Not Entered</div>
                        <div><span>Page on Site</span> :  http://www.companypage.com/pagecustomeronwhenchatinitiated/...</div>
                    </div>
                    <div class="large-6 columns">
                        <div>Initiated Chat (or reply to proactive chat)</div>
                        <div>Customer is using SMS (vs Chat on Site, or Chat on Mobile Site?</div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="tab-agent-content">
                    <div class="tab-agent-comment">
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">Hello, I need help with XYZ</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">
                                I will be happy to help you with XYZ, What is your questions?
                            </div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">
                                I’d like to know the dimensions, so it will fit
                            </div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">How can I help you?</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only  l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">I whould like to ask you questions.</div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="tab-agent-footer all-chats-box columns">
                    <div class="large-12 columns p-0">
                        <div class="large-10 medium-9 small-12 columns">
                            <form class="tab-agent-input large-12 small-12 v-middle m-r-10">
                                <input type="text" class="form-control">                                        
                            </form>
                            <a href="#" title="" class="form-que-img">
                                <img src="<?= $this->basePath(); ?>/images/question-icon.png">
                            </a>
                        </div>
                        <div class="large-2 medium-3 small-12 text-right p-0 small-m-t-10 columns">
                            <a class="button small radius m-r-10">SEND</a>
                            <a href="javascript:void(0)" class="transfer-chat-btn inline-block">
                                <img src="<?= $this->basePath(); ?>/images/pop-up-open.png" alt="" title="">
                            </a>
                        </div>
                        <div id="transfer-chat" class="transfer-chat-box"  style="display:none;">
                            <div class="large-12 columns transfer-title">
                                <input type="text" class="form-control" value="" placeholder="Enter Name"> 
                            </div>
                            <div class="large-12 columns transfer-btn">
                                <a href="#" title="Transfer Chat" class="button small radius">Transfer Chat</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="tabs-panel" id="panel3">
            <div class="tab-agent-detail">
                <div class="tab-agent-header">
                    <div class="large-6 columns">
                        <div><span>Customer Name</span> :  James</div>
                        <div><span>Customer Email</span> :  Not Entered</div>
                        <div><span>Page on Site</span> :  http://www.companypage.com/pagecustomeronwhenchatinitiated/...</div>
                    </div>
                    <div class="large-6 columns">
                        <div>Initiated Chat (or reply to proactive chat)</div>
                        <div>Customer is using SMS (vs Chat on Site, or Chat on Mobile Site?</div>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="tab-agent-content">
                    <div class="tab-agent-comment">
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">Hello, I need help with XYZ</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">I will be happy to help you with XYZ, What is your questions?</div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">I’d like to know the dimensions, so it will fit</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="small-3 large-2 columns l-name">Robert</div>
                            <div class="small-9 large-8 columns comments r-arrow">How can I help you?</div>
                            <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                        </div>
                        <div class="small-12 columns comment-box p-0 m-b-10">
                            <div class="large-2 columns hide-for-small-only  l-name">&nbsp;</div>
                            <div class="small-9 large-8 columns comments l-arrow">I whould like to ask you questions.</div>
                            <div class="small-3 large-2 columns r-name">James</div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
                <div class="tab-agent-footer all-chats-box columns">
                    <div class="large-12 columns p-0">
                        <div class="large-10 medium-9 small-12 columns">
                            <form class="tab-agent-input large-12 small-12 v-middle m-r-10">
                                <input type="text" class="form-control">                                        
                            </form>
                            <a href="#" title="" class="form-que-img">
                                <img src="<?= $this->basePath(); ?>/images/question-icon.png">
                            </a>
                        </div>
                        <div class="large-2 medium-3 small-12 text-right p-0 small-m-t-10 columns">
                            <a class="button small radius m-r-10">SEND</a>
                            <a href="javascript:void(0)" class="transfer-chat-btn inline-block">
                                <img src="<?= $this->basePath(); ?>/images/pop-up-open.png" alt="" title="">
                            </a>
                        </div>
                        <div id="transfer-chat" class="transfer-chat-box"  style="display:none;">
                            <div class="large-12 columns transfer-title">
                                <input type="text" class="form-control" value="" placeholder="Enter Name"> 
                            </div>
                            <div class="large-12 columns transfer-btn">
                                <a href="#" title="Transfer Chat" class="button small radius">Transfer Chat</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="tabs-panel" id="panel4">
            <div class='default'>
                <div id='jqxWidget' style="font-size: 13px; font-family: Verdana; float: left;">
                    <div id="jqxgrid"></div>
                </div>
            </div>
        </div> 
    </div>
     <?php //} 
     //else {?>
    <div class="">
<!--        <strong><h5>No Chat Available.</h5></strong>-->
    </div>
    <?php// }?>
</div>


<footer>
    <div class="row">		
        <div class="large-12 small-12 columns footer-text">
            Copyright 2016 <a href="<?= $this->url('home') ?>" title="LiveSupport" target="_blank">LiveSupport.com</a>   •   All Rights Reserved
        </div>
    </div>
</footer>

<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/foundation.min.js'); ?>"></script>
<script src="http://foundation.zurb.com/sites/docs/v/5.5.3/assets/js/modernizr.js"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcore.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxswitchbutton.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdata.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxbuttons.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxscrollbar.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxmenu.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.sort.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.filter.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.selection.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxpanel.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcheckbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxlistbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdropdownlist.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.pager.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/demos.js'); ?>"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var url = "data/chat-query.xml";
        // prepare the data
        var source =
                {
                    datatype: "xml",
                    datafields: [
                        {name: 'CustomerName', },
                        {name: 'CustomersEmailID', },
                        {name: 'ContactDetails', },
                        {name: 'QueueTime', },
                        {name: 'StartChat', }
                    ],
                    root: "entry",
                    record: "content",
                    id: 'ChatQueue',
                    url: url,
                    //sortcolumn: 'AgentName',
                    //sortdirection: 'asc'
                };
        var dataAdapter = new $.jqx.dataAdapter(source);

        // create jqxgrid.
        $("#jqxgrid").jqxGrid({
            width: '100%',
            //height: 450,
            autoheight: true,
            //autorowheight:true,
            columnsheight: 70,
            rowsheight: 70,
            pagerheight: 70,
            source: dataAdapter,
            sortable: true,
            pageable: true,
            showsortcolumnbackground: false,
            filterable: true,
            altrows: true,
            columns: [
                {
                    text: 'Queue No.', sortable: false, filterable: false, editable: false,
                    groupable: false, draggable: false, resizable: false,
                    datafield: '', columntype: 'number', width: '10%',
                    cellsrenderer: function (row, column, value) {
                        return "<div style='margin:25px 0 0 0; text-align:center;'>" + (value + 1) + "</div>";
                    }
                },
                {text: 'Customer Name', datafield: 'CustomerName', width: '25%'},
                {text: 'Customer&acute;s Email ID', datafield: 'CustomersEmailID', width: '20%'},
                {text: 'Contact Details', datafield: 'ContactDetails', width: '20%', cellsalign: 'left'},
                {text: 'Queue Time', datafield: 'QueueTime', width: '10%', cellsalign: 'left'},
                {text: 'Start Chat', datafield: 'StartChat', width: '15%', cellsalign: 'center'}
            ]
        });
    });

</script>
<script type="text/javascript">
    $(document).ready(function () {
        $(".transfer-chat-btn").click(function (e) {
            e.preventDefault();
            $("div#transfer-chat").toggle();
            $(".transfer-chat-btn").toggleClass("menu-open");
        });

        $("div#transfer-chat").mouseup(function () {
            return false
        });
        $(document).mouseup(function (e) {
            if ($(e.target).parent("a.transfer-chat-btn").length == 0) {
                $(".transfer-chat-btn").removeClass("menu-open");
                $("div#transfer-chat").hide();
            }
        });
    });
</script>

<script>
    $(document).foundation();
</script>

