<div class="off-canvas-wrapper">
	<div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
		<div class="off-canvas position-left" id="offCanvasLeft" data-off-canvas data-position="left">
			<button class="close-button" aria-label="Close menu" type="button" data-close> <span aria-hidden="true">&times;</span> </button>
			<ul class="mobile-ofc vertical menu">
				<li> <a href="http://zurb.com/responsive">Showcase</a>
					<ul class="submenu menu vertical" data-submenu>
						<li><a href="http://zurb.com/responsive">Foundation Showcase</a></li>
						<li><a href="http://foundation.zurb.com/showcase/brands.html">Brands</a></li>
						<li><a href="http://foundation.zurb.com/showcase/case-studies.html">Case Studies</a></li>
						<li><a href="http://foundation.zurb.com/showcase/blog.html">Blog</a></li>
						<li><a href="http://foundation.zurb.com/showcase/buzz.html">Buzz</a></li>
						<li><a href="http://foundation.zurb.com/showcase/about.html">About Foundation</a></li>
					</ul>
				</li>
				<li> <a href="http://foundation.zurb.com/develop/getting-started.html">Develop</a>
					<ul class="submenu menu vertical" data-submenu>
						<li class="title">Frameworks</li>
						<li><a href="http://foundation.zurb.com/sites.html">Foundation for Sites</a></li>
						<li><a href="http://foundation.zurb.com/emails.html">Foundation for Email</a></li>
						<li><a href="http://foundation.zurb.com/apps.html">Foundation for Apps</a></li>
						<li class="divider"></li>
						<li class="title">Develop</li>
						<li><a href="http://foundation.zurb.com/templates.html">HTML Templates</a></li>
						<li><a href="http://foundation.zurb.com/sites/resources.html">Resources</a></li>
						<li><a href="http://foundation.zurb.com/develop/building-blocks.html">Building Blocks</a></li>
						<li><a href="http://foundation.zurb.com/develop/yeti-launch.html">Yeti Launch</a></li>
						<li><a href="http://foundation.zurb.com/develop/contribute.html">Contribute</a></li>
					</ul>
				</li>
				<li> <a href="http://foundation.zurb.com/learn/tutorials.html">Tutorials</a>
					<ul class="submenu menu vertical" data-submenu>
						<li><a href="http://foundation.zurb.com/learn/tutorials.html">Tutorials</a></li>
						<li><a href="http://foundation.zurb.com/learn/classes.html">Classes</a></li>
						<li><a href="http://foundation.zurb.com/learn/custom-training.html">Custom Training</a></li>
						<li><a href="http://foundation.zurb.com/learn/certification.html">Certification</a></li>
						<li><a href="http://foundation.zurb.com/learn/responsive-reading.html">Responsive Reading</a></li>
					</ul>
				</li>
				<li> <a href="http://foundation.zurb.com/get-involved/support.html">Get Involved</a>
					<ul class="submenu menu vertical" data-submenu>
						<li><a href="http://foundation.zurb.com/get-involved/support.html">Connect</a></li>
						<li><a href="http://foundation.zurb.com/get-involved/premium-support.html">PLZ Halp</a></li>
						<li><a href="http://foundation.zurb.com/forum/sort/unanswered">Foundation Forum</a></li>
						<li><a href="http://foundation.zurb.com/learn/events.html">Events</a></li>
						<li><a href="http://foundation.zurb.com/get-involved/faq.html">FAQs</a></li>
						<li><a href="http://foundation.zurb.com/get-involved/contribute.html">Contribute</a></li>
						<li><a href="http://foundation.zurb.com/get-involved/yetinauts.html">Yetinauts</a></li>
					</ul>
				</li>
				<li> <a href="http://foundation.zurb.com/frameworks-docs.html">Docs</a>
					<ul class="submenu menu vertical" data-submenu>
						<li><a href="http://foundation.zurb.com/docs/" target="_blank">Sites Docs</a></li>
						<li><a href="http://foundation.zurb.com/apps/docs/#!/" target="_blank">Apps Docs</a></li>
						<li><a href="http://zurb.com/ink/docs.php" target="_blank">Email Docs</a></li>
					</ul>
				</li>
				<li><a href="http://foundation.zurb.com/develop/getting-started.html" class="button">Getting Started</a></li>
			</ul>
		</div>
		<div class="off-canvas-content" data-off-canvas-content>
			<header>
				<div class="large-12 medium-12 small-12  columns header-top-1">
					<div class="row">
						<div class="large-3 medium-3 small-12 float-left header-top-left"><a href="#"><i class="fa fa-facebook"></i></a> | <a href="#" title=""><i class="fa fa-twitter"></i></a> | <a href="#" title=""><i class="fa fa-pinterest-p"></i></a> | <a href="#" title=""><i class="fa fa-google-plus"></i></a></div>
						<div class="large-6 medium-6 small-12 float-left header-top-center">As a monetization tool or support service, you decide how it's used...</div>
						<div class="large-3 medium-3 small-12 float-left header-top-right"><a href="<?= $this->url('login') ?>" title="Account Login">Account Login</a> | <a href="<?= $this->url('signup') ?>" title="Register">Register</a></div>
					</div>
				</div>
				<div class="large-12 medium-12 small-12 columns header-top-2">
					<div class="row">
						<div class="large-3 small-12 float-left dashboard-top-bg">
							<div class="show-for-small-only mob-menu-icon">
								<button class="menu-icon" type="button" data-open="offCanvasLeft"></button>
							</div>
							<a href="<?= $this->url('home') ?>" title="Connect with me"><img src="<?= $this->basePath('images/logo.png') ?>" alt="Connect with me" title="Connect with me"></a> </div>
						<div class="large-9 small-12 float-right">
							<nav class="marketing-topbar show-for-medium">
								<ul class="dropdown menu" data-dropdown-menu data-click-open="false">
									<li> <a href="<?= $this->url('home') ?>">Home</a></li>
									<li> <a href="#" title="Product">Product</a> 
										<!--<ul class="submenu menu vertical" data-submenu>
							<li><a href="#" title="Product 1">Product 1</a></li>
							<li><a href="#" title="Product 2">Product 2</a></li>
							<li><a href="#" title="Product 3">Product 3</a></li>
						</ul>--> 
									</li>
									<li> <a href="#" title="Pricing">Pricing</a></li>
									<li> <a href="#" title="Feature">Feature</a></li>
									<li> <a href="#" title="Support">Support</a></li>
									<li> <a href="#" title="Contact Us">Contact Us</a></li>
								</ul>
							</nav>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</header>
                    <section>
				<div class="large-12 medium-12 small-12 columns index-center-main">
					<div class="index-details-box">
						<div class="large-12 small-12 columns index-box-row-1">The <strong>fastest way</strong> to help your customers</div>
						<div class="large-12 small-12 columns index-box-row-2">
							<div class="row">Start chatting with visitors who need your help using a free <strong>15-day trial</strong></div>
						</div>
						<div class="large-12 small-12 columns index-box-row-3 p-t-15 p-b-15">
							<div class="row"> <a href="<?= $this->url('signup') ?>" title="" class="btn btn-default float-left">Try Connect with me</a> <a href="<?= $this->url('login') ?>" title="" class="btn btn-reverse float-right">Login</a> </div>
						</div>
						<div class="large-12 small-12 columns index-box-row-4">By clicking "TRY CONNECT WITH ME" you agree to the Connect with Me Terms & Conditions and Privacy Policy.</div>
					</div>
				</div>
			</section>
                        <?= $this->content ?>			
			<footer>
				<div class="large-12 small-12 columns p-t-20">
					<div class="row">
						<div class="large-12 small-12 columns footer-links"><a href="<?= $this->url('home') ?>" title="Home">Home</a> | <a href="#" title="About Us">About Us</a> | <a href="#" title="Contact Us">Contact Us</a> | <a href="#" title="Privacy Policy">Privacy Policy</a> | <a href="#" title="Terms & Conditions">Terms & Conditions</a> | <a href="#" title="Sitemap">Sitemap</a> </div>
						<div class="large-12 small-12 columns footer-text"> Copyright 2016 <a href="index.html" title="ConnectWithMe" target="_blank">ConnectWithMe.com</a> &bull;   All Rights Reserved </div>
					</div>
				</div>
			</footer>
		</div>
	</div>
</div>