<?= $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8">
         <?= $this->headTitle('Connect With me...')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'images/favicon.png', 'href' => $this->basePath() . '/images/favicon.png'])
            ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/foundation.min.css'))
        ?>

        <!-- Scripts -->
        
        <?php 
        
        //$this->headScript()
//            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
        ?>
</head>
<body class="login-bg">

<?= $this->content ?>
    
</body>
</html>
