<?= $this->doctype() ?>
<html>

    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Connect With me...')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?=
                $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        <link href="http://cdnjs.cloudflare.com/ajax/libs/foundicons/3.0.0/foundation-icons.css" rel="stylesheet" />

        <!-- styles -->
        <?=
                $this->headLink(['rel' => 'shortcut icon', 'type' => 'images/favicon.png', 'href' => $this->basePath() . '/images/favicon.png'])
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/foundation.min.css'))
                ->prependStylesheet($this->basePath('css/jqx.base.css'))
                ->prependStylesheet($this->basePath('css/docs.css'))
        ?>

    </head>
    <body>
        <div>
            <div class="row white-bg">
                <div class="large-2 small-12 columns left-column">
                    <div class="logo-box">
                        <a class="logo" href="<?= $this->url('home') ?>">
                            <img src="<?= $this->basePath('images/logo.png'); ?>" alt="" title="">
                        </a>
                    </div>
                    <div class="side-menu hide-for-small-only">
                        <ul>
                            <li class="active dashboard"><a href="<?= $this->basePath('admin') ?>" title="">Dashboard</a></li>
                            <li class="user-search"><a href="<?= $this->basePath('admin/userSearch') ?>" title="">User Search</a></li>
                            <li class="change-password"><a href="javascript:void(0)" title="">Change Password</a></li>
                            <li class="logout"><a href="javascript:void(0)" title="">Logout</a></li>
                        </ul>
                    </div>
                </div>
                <div class="large-10 small-12 columns main-content grey-bg p-0">
                    <div class="blue-bg text-right p-5"> 
                        <span class="user"> 
                            <span>
                                <img src="<?= $this->basePath('images/user.png'); ?>" alt="" title="">
                            </span> 
                            <span>
                                Welcome<strong>John Millar</strong>
                            </span> 
                        </span> 
                        <span class="login-logout"><a href="<?= $this->url('login') ?>" class="logout">Logout</a></span> 
                    </div>

                    <?= $this->content ?>
                </div>
            </div></div>
    </body>
</html>
