<?= $this->doctype() ?>
<html>
    <head>
        <meta charset="utf-8">

        <?= $this->headTitle('Connect With me...')->setSeparator(' - ')->setAutoEscape(false) ?>
        <link rel="icon" href="images/favicon.png">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
        <link rel="stylesheet" href="<?= $this->basePath('css/docs.css') ?>">
        <link rel="stylesheet" href="<?= $this->basePath('css/foundation.min.css') ?>">
        <link rel="stylesheet" href="<?= $this->basePath('css/font-awesome.min.css') ?>">
        <!--<link rel="stylesheet" href="css/style.css">-->
        <link rel="stylesheet" href="<?= $this->basePath('css/custom-chat-box.css') ?>">
        <!-- Custom CSS Write -->
        <style>
            .button { background: <?= $data->background_color ?> !important; font-family: '<?= $data->font ?>', sans-serif !important; margin: 0px; padding: 15px 20px; color: <?= $data->text_color ?> !important; border-color:<?= $data->border_color ?> !important;
            }
            <?php
            if ($data->button_dimension == "Small") {
                ?>
                .step1 {width:180px;}
                <?php
            } elseif ($data->button_dimension == "Medium") {
                ?>
                .step1 {width:250px;}
                <?php
            } elseif ($data->button_dimension == "Large") {
                ?>    
                .step1 {width:300px;}
            <?php }
            ?>
            .chat-box-type-1-header {font-family: '<?= $data->open_font ?>', sans-serif !important; background:<?= $data->open_background_color ?> !important; color:<?= $data->open_text_color ?> !important;border-color:<?= $data->open_border_color ?>;                         
            }
            .bubbel-btn {
                font-family: '<?= $data->pro_font ?>', sans-serif !important; 

                background:<?= $data->pro_background_color ?> !important;

                color:<?= $data->pro_text_color ?> !important;

                border-color:<?= $data->pro_border_color ?> !important;
            }
            .bubbel-btn:after {
                border-top:10px solid <?= $data->pro_background_color ?> !important;
            }
            <?php
            if ($data->button_location == "right") {
                ?>
                .chat-box  {right:0px;}
                <?php
            } else {
                ?>
                .chat-box  {right:inherit;left:0px;}
            <?php } ?>

            

        </style>
        <!-- -->
    </head>
    <body class="login-bg white-bg">

        <?= $this->content ?>
    </body>
</html>