<body class="login-bg">
    <div class="row register-box register-thank-you-box">
        <div class="large-12 columns logo"> 
            <a href="<?= $this->url('home') ?>" title="Live Support">
                <img src="<?= $this->basePath("images/logo.png") ?>" alt="Live Support" title="Live Support">
            </a> 
        </div>
        <div class="large-12 columns thankyou-msg">
            Thank you for confirming your email address <br><br>
            <a href="<?= $this->url('login') ?>" title="" class="btn btn-default">Login Here</a>
        </div>
    </div>

    <script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js') ?>"></script>
    <script src="<?= $this->basePath('js/foundation.min.js') ?>"></script>

</body>
</html>
