<body class="login-bg">
<div class="row register-box register-thank-you-box">
	<div class="large-12 columns logo"> 
            <a href="<?= $this->url('home') ?>" title="Connect with Me">
                <img src="<?= $this->basePath("images/logo.png") ?>" alt="Connect with Me" title="Connect with Me">
            </a> 
        </div>
	<div class="large-12 columns thankyou-msg">
		Thank you for Register.Please Confirm your Email <br><br>
		<a href="<?= $this->url('signup') ?>" title="" class="btn btn-default">Click Here</a>
	</div>
</div>
    
<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js') ?>"></script>
<script src="<?= $this->basePath('js/foundation.min.js') ?>"></script>

</body>
</html>
