<?php
$this->session=new Zend\Session\Container('base');

$manager_id=$form->get('manager_id');
$manager_id->setValue($this->session->offsetGet('user_id'));

$font = $form->get('font');
$font->setValueOptions([''=>'Select Font','Lato'=>'Lato','Roboto'=>'Roboto','Lora'=>'Lora']);
$font->setAttribute('class','select-style');

$background_color=$form->get('background_color');
$background_color->setAttribute('id','background_color');

$text_color=$form->get('text_color');
$text_color->setAttribute('id','text_color');

$button_text=$form->get('button_text');
$button_text->setAttribute('class','form-control p-0 p-l-10');
$button_text->setAttribute('placeholder','Enter Button Text');
$button_text->setAttribute('maxlength', '15');

$border_color=$form->get('border_color');
$border_color->setAttribute('id','border_color');

$button_dimension = $form->get('button_dimension');
$button_dimension->setValueOptions([''=>'Select Button Dimensions','small'=>'Small','medium' => 'Medium','large' => 'Large']);
$button_dimension->setAttribute('class','select-style');

$button_location = $form->get('button_location');
$button_location->setValueOptions([''=>'Select Button Location','left'=>'Left','right' => 'Right']);
$button_location->setAttribute('class','select-style');

$open_font=$form->get('open_font');
$open_font->setAttribute('class','select-style');
$open_font->setValueOptions([''=>'Select Font','Lato'=>'Lato','Roboto'=>'Roboto','Lora' => 'Lora']);

$open_background_color=$form->get('open_background_color');
$open_background_color->setAttribute('id','open_background_color');

$open_text_color=$form->get('open_text_color');
$open_text_color->setAttribute('id','open_text_color');

$open_border_color=$form->get('open_border_color');
$open_border_color->setAttribute('id','open_border_color');

$open_desktop_dimension=$form->get('open_desktop_dimension');
$open_desktop_dimension->setAttribute('class','select-style');
$open_desktop_dimension->setValueOptions([''=>'Select Chat Box Dimensions for Desktop','small'=>'Small','medium' => 'Medium','large' => 'Large']);

$open_mobile_dimension=$form->get('open_mobile_dimension');
$open_mobile_dimension->setAttribute('class','select-style');
$open_mobile_dimension->setValueOptions([''=>'Select Chat Box Dimensions for Mobile','small'=>'Small','medium' => 'Medium','large' => 'Large']);

$open_tablet_dimension=$form->get('open_tablet_dimension');
$open_tablet_dimension->setAttribute('class','select-style');
$open_tablet_dimension->setValueOptions([''=>'Select Chat Box Dimensions for Tablet','small'=>'Small','medium' => 'Medium','large' => 'Large']);

$pro_font=$form->get('pro_font');
$pro_font->setAttribute('class','select-style');
$pro_font->setValueOptions([''=>'Select Font','Lato'=>'Lato','Roboto'=>'Roboto','Lora' => 'Lora']);

$pro_background_color=$form->get('pro_background_color');
$pro_background_color->setAttribute('id','pro_background_color');

$pro_text_color=$form->get('pro_text_color');
$pro_text_color->setAttribute('id','pro_text_color');

$pro_border_color=$form->get('pro_border_color');
$pro_border_color->setAttribute('id','pro_border_color');

$submit = $form->get('submit');
$submit->setAttribute('class','btn btn-default');

?>
<div class="header-bg">
    <div class="header-title">CHAT DESIGN SETUP</div>
</div>
<div class="main-content">
    <div class="text-center note-box">
        <div>Copy the code below and place it into the footer of your website.</div>
        <div>You can change the display and options of your chat buttons and proactive messages at any time by changing the below options</div>
    </div>
    <div class="row">
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Chat Button</div>
                <?php
            $form->setAttribute('action', $this->url('chatdesign'));
            $form->setAttribute('class', 'small-12 columns p-0');
            $form->prepare();
            echo $this->form()->openTag($form);
            ?>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($font) ?>
                                <?= $this->formElement($manager_id) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($background_color) ?>
                                <div id="dropDownButton">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker"> 
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($background_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($text_color) ?>    
                                <div id="dropDownButton1">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker1">
                                             
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($text_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                                        <?= $this->formElement($button_text) ?>
                                        <?= $this->formElementErrors()->render($button_text) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($border_color) ?>        
                                <div id="dropDownButton2">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker2"> 
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($border_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                    <?= $this->formElement($button_dimension) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                    <?= $this->formElement($button_location) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20"> 
                        <?= $this->formElement($submit) ?>
                    </div>
                
            </div>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Open Chat Box</div>
                
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_font) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_background_color) ?>
                                <div id="dropDownButton3">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker3"> </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($open_background_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_text_color) ?>
                                <div id="dropDownButton4">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker4"> </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($open_text_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_border_color) ?>
                                <div id="dropDownButton5">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker5"> </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($open_border_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_desktop_dimension) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_mobile_dimension) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($open_tablet_dimension) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20"> 
                        <?= $this->formElement($submit) ?>
                    </div>
                
            </div>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Proactive Chat Message</div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($pro_font) ?>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($pro_background_color) ?>
                                <div id="dropDownButton6">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker6"> </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($pro_background_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($pro_text_color) ?>
                                <div id="dropDownButton7">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker7"> </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($pro_text_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <?= $this->formElement($pro_border_color) ?>
                                <div id="dropDownButton8">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker8">
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?= $this->formElementErrors()->render($pro_border_color) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select class="select-style">
                                    <option>Select Chat Box Dimensions for Desktop</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select class="select-style">
                                    <option>Select Chat Box Dimensions for Mobile</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select class="select-style">
                                    <option>Select Chat Box Dimensions for Tablet</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20"> 
                        <?= $this->formElement($submit) ?>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
        <div class="small-12 medium-12 columns m-t-30">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Open Chat Box</div>
                <form class="small-12 columns p-0 p-t-10">
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Tell customers in queue what number they are.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Display agent image.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Display link to URL that customer previously on.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Allow customer SMS (Text Messaging) option.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Show department agent assigned to.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline">
                                <input class="checkbox-inline" type="checkbox">
                                Display help files / FAQ URL to customer</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="small-12 medium-12 columns m-t-30 p-0">
            <div class="small-12 medium-12 large-5 columns">
                <div class="small-12 medium-12 columns p-0">
                    <div class="create-agent-bg columns">
                        <div class="add-agent-title">Paste This Code Into Your Site on Footer Section</div>
                        <div class="form">
                            <textarea rows="10" cols="50">
<!-- CHAT INSERTION DEMO CODE -->
<div id="demo"></div>
<script src="http://bit.ly/2etBlAr"></script>
<script src="http://bit.ly/2etKA5n"></script>
<script type="text/javascript">$("#viewclick").click(function(){ $('.chat-btn').hide(); $('.chat-box').show(); });</script>
<!-- CODE INSERTION COMPLETED -->
                            </textarea>
                            <div class="btn-side"><a href="javascript:void(0)" class="btn btn-default">Copy</a></div>
                        </div>
                    </div>
                </div>
                <div class="small-12 medium-12 columns p-0">
                    <div class="create-agent-bg m-t-30 columns">
                        <div class="add-agent-title">Paste Your Custom CSS Here</div>
                        <div class="form">
                            <pre>.row { margin: 0 auto; max-width: 55.55556rem; width: 100%; }
.row:before, .row:after { content: " "; display: table; }
.row:after { clear: both; }
.row.collapse > .column,  .row.collapse > .columns { padding-left: 0; padding-right: 0; }
.row.collapse .row { margin-left: 0; margin-right: 0; }
.row .row { margin: 0 -0.83333rem; max-width: none; width: auto; }
.row .row:before, .row .row:after { content: " "; display: table; }
.row .row:after { clear: both; }
.row .row.collapse { margin: 0; max-width: none; width: auto; }
.row .row.collapse:before, .row .row.collapse:after { content: " "; display: table; }
.row .row.collapse:after { clear: both; }
.column, .columns { padding-left: 0.83333rem; padding-right: 0.83333rem; width: 100%; float: left; }

                            </pre>
                            <div class="btn-side"><a href="javascript:void(0)" class="btn btn-default">PREVIEW</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="small-12 medium-12 large-7 columns">
                <div class="create-agent-bg columns">
                    <div class="add-agent-title">Preview of Above Selection</div>
                    <div class="form" style="min-height:625px; position:relative;">
                        
                            <!--<iframe id="iFrame1" width="100%" height="500" src="chat.html" style="height:600px !important; width:100% !important;" frameborder="0"></iframe> -->
                        <!-- <div class="" style="margin-top: 0px; margin-right: 0px; margin-bottom: 0px; padding: 0px; border: 0px none; background: transparent none repeat scroll 0% 0%; overflow: hidden; position: fixed; z-index: 16000002; width: 180px; height: 30px; right: 10px; bottom: 0px;"> -->
                        <iframe src="<?= $this->url('chatpreview') ?>" style="background-color: transparent; vertical-align: text-bottom; position: relative; width: 100%; height: 600px; min-width: 100%; min-height: 100%; max-width: 100%; max-height: 100%; margin: 0px; overflow: hidden; display: block;" scrolling="no" frameborder="0"></iframe>
                        <!--</div> -->
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</div>
<footer>
    <div class="row">
        <div class="large-12 small-12 columns footer-text"> Copyright 2016 <a href="index.html" title="LiveSupport" target="_blank">LiveSupport.com</a> •   All Rights Reserved </div>
    </div>
</footer>
<!--<script type="text/javascript" src="js/jquery-1.12.3.min.js"></script>  -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<!--<script type="text/javascript" src="js/iframeResizer.js"></script>-->
<script type="text/javascript" src=<?= $this->basePath('js/modernizr.js'); ?>></script> 
<script src="http://foundation.zurb.com/sites/docs/assets/js/vendor.js"></script> 
<script src="http://foundation.zurb.com/sites/docs/assets/js/foundation.js"></script> 
<script src="http://foundation.zurb.com/sites/docs/assets/js/docs.js"></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxcore.js'); ?>></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxcolorpicker.js'); ?>></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxradiobutton.js'); ?>></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxdropdownbutton.js'); ?>></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxscrollview.js'); ?>></script> 
<script type="text/javascript" src=<?= $this->basePath('js/jqxbuttons.js'); ?>></script> 
<script type="text/javascript">
    /*Color Picker*/
    function getTextElementByColor(color) {
        if (color == 'transparent' || color.hex == "") {
            return $("<div style='text-shadow: none; position: relative; padding-bottom: 2px; margin-top: 2px;'>transparent</div>");
        }
        var element = $("<div style='text-shadow: none; position: relative; padding-bottom: 2px; margin-top: 2px;'>#" + color.hex + "</div>");
        var nThreshold = 105;
        var bgDelta = (color.r * 0.299) + (color.g * 0.587) + (color.b * 0.114);
        var foreColor = (255 - bgDelta < nThreshold) ? 'Black' : 'White';
        element.css('color', foreColor);
        element.css('background', "#" + color.hex);
        element.addClass('jqx-rc-all');
        return element;
    }
    $(document).ready(function () {
        /**/
        var background_color=$('#background_color').val();
        $("#colorPicker").jqxColorPicker('setColor', '#bbaaff');
        
        $("#colorPicker").on('colorchange', function (event) {
            $("#dropDownButton").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#background_color').val(hex);
        });
        $("#colorPicker").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker1").on('colorchange', function (event) {
            $("#dropDownButton1").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker1").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#text_color').val(hex);
        });
        $("#colorPicker1").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton1").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton1").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker2").on('colorchange', function (event) {
            $("#dropDownButton2").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker2").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#border_color').val(hex);
        });
        $("#colorPicker2").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton2").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton2").jqxDropDownButton('setContent', 'Select Border Color');
        /**/
        $("#colorPicker3").on('colorchange', function (event) {
            $("#dropDownButton3").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker3").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#open_background_color').val(hex);
        });
        $("#colorPicker3").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton3").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton3").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker4").on('colorchange', function (event) {
            $("#dropDownButton4").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker4").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#open_text_color').val(hex);
        });
        $("#colorPicker4").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton4").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton4").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker5").on('colorchange', function (event) {
            $("#dropDownButton5").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker5").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#open_border_color').val(hex);
        });
        $("#colorPicker5").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton5").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton5").jqxDropDownButton('setContent', 'Select Border Color');
        /**/
        $("#colorPicker6").on('colorchange', function (event) {
            $("#dropDownButton6").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker6").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#pro_background_color').val(hex);
        });
        $("#colorPicker6").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton6").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton6").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker7").on('colorchange', function (event) {
            $("#dropDownButton7").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker7").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#pro_text_color').val(hex);
        });
        $("#colorPicker7").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton7").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton7").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker8").on('colorchange', function (event) {
            $("#dropDownButton8").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
            var color = $("#colorPicker8").jqxColorPicker('getColor');
            var hex = "#"+color.hex;
            $('#pro_border_color').val(hex);
        });
        $("#colorPicker8").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton8").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton8").jqxDropDownButton('setContent', 'Select Border Color');
    });
</script>
