<?php 
$first_name = $form->get('first_name');
$first_name->setAttribute('class', 'form-control name-icon');
$first_name->setAttribute('maxlength','20');
$first_name->setAttribute('placeholder', 'First Name');

$last_name = $form->get('last_name');
$last_name->setAttribute('class', 'form-control name-icon');
$last_name->setAttribute('maxlength','20');
$last_name->setAttribute('placeholder', 'Last Name');

$email = $form->get('email');
$email->setAttribute('class', 'form-control login-icon');
$email->setAttribute('maxlength','30');
$email->setAttribute('placeholder', 'Email');


$photo = $form->get('photo');
$photo->setAttribute('class', 'form-control upload-agent-image-icon');


$department = $form->get('department');
$department->setAttribute('class', 'select-style');
$department->setValueOptions(["Customer Service"=>"Customer Service","Sales"=>"Sales","Administrator"=>"Administrator","Marketing"=>"Marketing"]);
//$departments = $form->get('departments');
//$departments->setAttribute('id','departments');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');
?>
<div class="header-bg">
    <div class="header-title">CURRENT AGENTS</div>
</div>
<div class="side-menu show-for-small-only">
    <ul>
        <li class="stats"><a href="<?= $this->basePath('manager'); ?>" title="">Stats</a></li>
        <li class="curr-chat"><a href="current-chat.html" title="">Current Chats</a></li>
        <li class="active agent-setup"><a href="<?= $this->basePath('manager/agentSetup'); ?>" title="">Agent Setup</a></li>
        <li class="chat-setup"><a href="<?= $this->basePath('manager/chatSetup'); ?>" title="">Chat Setup</a></li>
        <li class="chat-design"><a href="<?= $this->basePath('manager/chatDesign'); ?>" title="">Chat Design</a></li>
        <li class="report"><a href="javascript:void(0)" title="">Reports</a></li>
        <li class="account"><a href="<?= $this->basePath('manager/accountSettings'); ?>" title="">Accounts</a></li>
    </ul>
</div>
<div class="main-content">
    <div class='default'>
        <div id='jqxWidget' style="font-size: 13px; font-family: Verdana; float: left;">
            <div id="jqxgrid"> </div>
        </div>
    </div>
    <div class="row" style="width:auto">
        <div class="large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Create Agent</div>
                <?php 
		$form->setAttribute('action', $this->url('manager', ['action' => 'agentSetup']));
                $form->setAttribute('class','larger-12');
                $form->prepare();
                echo $this->form()->openTag($form);?>
                    <div class="large-6 columns">
                        <div class="form-group form-group-box m-t-20">
                            <?= $this->formElement($first_name) ?>
                            <?= $this->formElementErrors()->render($first_name) ?>
                        </div>
                    </div>
                    <div class="large-6 columns">
                        <div class="form-group form-group-box m-t-20">
                            <?= $this->formElement($last_name) ?>
                            <?= $this->formElementErrors()->render($last_name) ?>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <?= $this->formElement($email) ?>
                            <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
                        </div>
                    </div>
                    <div class="large-12 columns" id="dept">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box employee-icon">
                                <div class="select">
                                    <?= $this->formElement($department) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="large-12 small-12 columns p-0 upload-agent-image">
                                <?= $this->formElement($photo) ?>
                                <?= $this->formElementErrors()->render($photo, ['class' => 'help-block']) ?>
<!--                                <input placeholder="Upload Agent Image" value="" class="form-control upload-agent-image-icon" type="email">
                                <a href="#" title="" class="btn upload-agent-image-btn">Browse</a> </div>-->
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group cennter m-t-30 m-b-30"> <?php echo $this->formSubmit($submit);
                        echo $this->formHidden($form->get('agent_id')); ?> </div>
                    </div>
                <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
        <div class="large-8 columns">
            <div class="agent-setting-bg columns">
                <div class="add-agent-title">Agent Settings &amp; Distribution</div>
                <form class="small-12 columns p-0">
                    <div class="large-12 columns bg-1">
                        <div class="large-9 columns text-1"> Maximum number of chats agent can have concurrent </div>
                        <div class="large-3 columns">
                            <div class="form-group">
                                <input placeholder="" value="" class="form-control" type="number">
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns bg-2">
                        <div class="large-9 columns text-1"> Agents can re-assign chats to other department / manager </div>
                        <div class="large-3 columns">
                            <div class="select-control-box">
                                <select >
                                    <option>Yes</option>
                                    <option>Yes</option>
                                    <option>No</option>
                                </select>

                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns bg-1">
                        <div class="large-9 columns text-1"> Agents can pull chats from queue </div>
                        <div class="large-3 columns">
                            <div class="select-control-box">
                                <select >
                                    <option>Yes</option>
                                    <option>Yes</option>
                                    <option>No</option>
                                </select>

                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns bg-2">
                        <div class="large-9 columns text-1"> Chats evenly distributed to all available agents</div>
                        <div class="large-3 columns">
                            <div class="select-control-box">
                                <select >
                                    <option>Yes</option>
                                    <option>Yes</option>
                                    <option>No</option>
                                </select>

                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns bg-1">
                        <div class="large-9 columns text-1"> Time before chat is redistributed if not answered by agent </div>
                        <div class="large-3 columns">
                            <div class="form-group">
                                <div class="select-control-box">
                                    <select>
                                        <option>3 Minutes</option>
                                        <option>5 Minutes</option>
                                        <option>7 Minutes</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group cennter m-t-30 m-b-30"> <a href="#" title="" class="btn btn-default">SUBMIT</a> </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="clearfix">&nbsp;</div>
</div>

<footer>
    <div class="row">
        <div class="large-12 small-12 columns footer-text"> Copyright 2016 <a href="index.html" title="LiveSupport" target="_blank">LiveSupport.com</a> •   All Rights Reserved </div>
    </div>
</footer>
<style>
   input[type="file"] {line-height:inherit; height:auto; padding:10px 10px 13px;}
   </style>
<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/foundation.min.js'); ?>"></script>
<script src="http://foundation.zurb.com/sites/docs/v/5.5.3/assets/js/modernizr.js"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcore.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxswitchbutton.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdata.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxbuttons.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxscrollbar.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxmenu.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.sort.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.filter.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.selection.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxpanel.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcheckbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxlistbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdropdownlist.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.pager.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/demos.js'); ?>"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var url = "getAgent";
        // prepare the data
        var source =
                {
                    datatype: "json",
                    datafields: [
                        {name: 'agent_id'},
                        {name: 'first_name'},
                        {name: 'last_name'},
                        {name: 'email'},
                        {name: 'department'},
                        {name: 'status'}
                    ],
                    root: "data",
                    id: 'agent_id',
                    url: url
                    //sortcolumn: 'AgentName',
                    //sortdirection: 'asc'
                };
        var dataAdapter = new $.jqx.dataAdapter(source);
        var i = 0;
        // create jqxgrid.
        $("#jqxgrid").jqxGrid({
            width: '100%',
            //height: 450,
            autoheight: true,
            //autorowheight:true,
            columnsheight: 50,
            rowsheight: 50,
            pagerheight: 50,
            source: dataAdapter,
            sortable: true,
            pageable: true,
            showsortcolumnbackground: false,
            filterable: true,
            altrows: true,
            columns: [
                {text: 'Agent Name', datafield: 'first_name', width: '15%'},
                {text: 'Last Name', datafield: 'last_name', width: '15%'},
                {text: 'Email', datafield: 'email', width: '15%'},
                {text: 'Department', datafield: 'department', width: '20%'},
                {text: 'Completed Chats', datafield: 'Completed', width: '15%', cellsalign: 'center', cellsRenderer: function (row, column, value) {
                        
                        // render custom column.
                        button = '<div class="jqx-grid-cell-middle-align" style="margin-top: 16.5px;"><span>15</span> <a class="linking" href="#"><i class="fi-eye"></i></a></div>'
                        return button;
                    }},
                {text: 'Current Chats', datafield: 'Current', width: '10%', cellsalign: 'center', cellsRenderer: function (row, column, value) {
                        
                        // render custom column.
                        button = '<div class="jqx-grid-cell-middle-align" style="margin-top: 16.5px;"><span>01</span> <a class="linking" href="#"><i class="fi-eye"></i></a></div>'
                        return button;
                    }},
                {text: 'Available', datafield: 'status', width: '10%', cellsalign: 'center', cellsRenderer: function (row, column, value) {
                        var check = "";
                        i++;
                        
                        if (value == "Yes") { var check = "checked = 'checked'";}
                        
                        // render custom column.
                        button = '<div class="jqx-grid-cell-middle-align" style="margin-top: 16.5px;"><div class="switch round tiny"><input id="' + i + '" type="checkbox" ' + check + ' onChange="statusChange('+i+')"><label for="' + i + '"></label></div></div>'
                        return button;
                    }
              }
            ]
        });
    });
    
    function statusChange(id){
       var status = document.getElementById(id).value;
       alert(status);
    }

</script>
</body>