<div class="header-bg">
    <div class="header-title">CHAT DESIGN SETUP</div>
</div>
<div class="side-menu show-for-small-only">
    <ul>
        <li class="stats"><a href="<?= $this->basePath('manager'); ?>" title="">Stats</a></li>
        <li class="curr-chat"><a href="<?= $this->basePath('manager/allChat'); ?>" title="">Current Chats</a></li>
        <li class="agent-setup"><a href="<?= $this->basePath('manager/agentSetup'); ?>" title="">Agent Setup</a></li>
        <li class="chat-setup"><a href="<?= $this->basePath('manager/chatSetup'); ?>" title="">Chat Setup</a></li>
        <li class="active chat-design"><a href="<?= $this->basePath('manager/chatDesign'); ?>" title="">Chat Design</a></li>
        <li class="report"><a href="javascript:void(0)" title="">Reports</a></li>
        <li class="account"><a href="<?= $this->basePath('manager/accountSettings'); ?>" title="">Accounts</a></li>
    </ul>
</div>
<div class="main-content">           
    <div class="text-center note-box">
        <div>Copy the code below and place it into the footer of your website.</div>
        <div>You can change the display and options of your chat buttons and proactive messages at any time by changing the below options</div>
    </div>
    <div class="row">
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Chat Button</div>
                <form class="small-12 columns p-0">
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Font</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton1">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker1">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Text Color</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton2">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker2">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Button Dimensions</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Button Location</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20">
                        <a class="btn btn-default">SAVE</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Open Chat Box</div>
                <form class="small-12 columns p-0">
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Font</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton3">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker3">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton4">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker4">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                            
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton5">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker5">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Desktop</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Mobile</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Tablet</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20">
                        <a class="btn btn-default">SAVE</a>
                    </div>
                </form>
            </div>
        </div>
        <div class="small-12 medium-12 large-4 columns">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Proactive Chat Message</div>
                <form class="small-12 columns p-0">
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Font</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton6">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker6">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton7">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker7">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>                            
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <div id="dropDownButton8">
                                    <div style="padding: 3px;">
                                        <div id="colorPicker8">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Desktop</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Mobile</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns">
                        <div class="form-group form-group-box m-t-20">
                            <div class="select-control-box p-l-r-10">
                                <select>
                                    <option>Select Chat Box Dimensions for Tablet</option>
                                    <option>Option 1</option>
                                    <option>Option 2</option>
                                    <option>Option 3</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="large-12 columns text-center m-t-20 m-b-20">
                        <a class="btn btn-default">SAVE</a>
                    </div>
                </form>
            </div>
        </div>

        <div class="small-12 medium-12 columns m-t-30">
            <div class="create-agent-bg columns">
                <div class="add-agent-title">Open Chat Box</div>
                <form class="small-12 columns p-0 p-t-10">
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Tell customers in queue what number they are.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Display agent image.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Display link to URL that customer previously on.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Allow customer SMS (Text Messaging) option.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Show department agent assigned to.</label>
                        </div>
                    </div>
                    <div class="small-12 medium-12 large-4 columns">
                        <div class="form-group">
                            <label class="checkbox-inline"><input class="checkbox-inline" type="checkbox"> Display help files / FAQ URL to customer</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>  

        <div class="small-12 medium-12 columns m-t-30 p-0">
            <div class="small-12 medium-12 large-7 columns">
                <div class="small-12 medium-12 columns p-0">
                    <div class="create-agent-bg columns">
                        <div class="add-agent-title">Paste This Code Into Your Site on Footer Section</div>
                        <div class="form">
                            <figure><img src="<?= $this->basePath('images/custom-script.jpg'); ?>" alt="" title=""></figure>
                            <div class="btn-side"><a href="javascript:void(0)" class="btn btn-default">Copy</a></div>
                        </div>
                    </div>
                </div>
                <div class="small-12 medium-12 columns p-0">
                    <div class="create-agent-bg m-t-30 columns">
                        <div class="add-agent-title">Paste Your Custom CSS Here</div>
                        <div class="form">
                            <figure><img src="<?= $this->basePath('images/custom-css.jpg'); ?>" alt="" title=""></figure>
                            <div class="btn-side"><a href="javascript:void(0)" class="btn btn-default">PREVIEW</a></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="small-12 medium-12 large-5 columns">
                <div class="create-agent-bg columns">
                    <div class="add-agent-title">Preview of Above Selection</div>
                    <div class="form" style="min-height:490px;">
                    </div>
                </div>
            </div>
        </div>

    </div>                

</div>

<footer>
    <div class="row">		
        <div class="large-12 small-12 columns footer-text">
            Copyright 2016 <a href="<?= $this->url('home') ?>" title="ConnectWithMe" target="_blank">ConnectWithMe.com</a>   •   All Rights Reserved
        </div>
    </div>
</footer>
<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js'); ?>"></script> 

<script src="http://foundation.zurb.com/sites/docs/v/5.5.3/assets/js/modernizr.js"></script>
<script src="http://foundation.zurb.com/sites/docs/assets/js/vendor.js"></script> 
<script src="http://foundation.zurb.com/sites/docs/assets/js/foundation.js"></script> 
<script src="http://foundation.zurb.com/sites/docs/assets/js/docs.js"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcore.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcolorpicker.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxradiobutton.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxdropdownbutton.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxscrollview.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxbuttons.js'); ?>"></script>


<script type="text/javascript">
    /*Color Picker*/
    function getTextElementByColor(color) {
        if (color == 'transparent' || color.hex == "") {
            return $("<div style='text-shadow: none; position: relative; padding-bottom: 2px; margin-top: 2px;'>transparent</div>");
        }
        var element = $("<div style='text-shadow: none; position: relative; padding-bottom: 2px; margin-top: 2px;'>#" + color.hex + "</div>");
        var nThreshold = 105;
        var bgDelta = (color.r * 0.299) + (color.g * 0.587) + (color.b * 0.114);
        var foreColor = (255 - bgDelta < nThreshold) ? 'Black' : 'White';
        element.css('color', foreColor);
        element.css('background', "#" + color.hex);
        element.addClass('jqx-rc-all');
        return element;
    }
    $(document).ready(function () {
        /**/
        $("#colorPicker").on('colorchange', function (event) {
            $("#dropDownButton").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker1").on('colorchange', function (event) {
            $("#dropDownButton1").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker1").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton1").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton1").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker2").on('colorchange', function (event) {
            $("#dropDownButton2").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker2").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton2").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton2").jqxDropDownButton('setContent', 'Select Border Color');
        /**/
        $("#colorPicker3").on('colorchange', function (event) {
            $("#dropDownButton3").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker3").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton3").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton3").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker4").on('colorchange', function (event) {
            $("#dropDownButton4").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker4").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton4").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton4").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker5").on('colorchange', function (event) {
            $("#dropDownButton5").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker5").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton5").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton5").jqxDropDownButton('setContent', 'Select Border Color');
        /**/
        $("#colorPicker6").on('colorchange', function (event) {
            $("#dropDownButton6").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker6").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton6").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton6").jqxDropDownButton('setContent', 'Select Background Color');
        /**/
        $("#colorPicker7").on('colorchange', function (event) {
            $("#dropDownButton7").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker7").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton7").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton7").jqxDropDownButton('setContent', 'Select Text Color');
        /**/
        $("#colorPicker8").on('colorchange', function (event) {
            $("#dropDownButton8").jqxDropDownButton('setContent', getTextElementByColor(event.args.color));
        });
        $("#colorPicker8").jqxColorPicker({color: "ffaabb", colorMode: 'hue', width: 220, height: 220});
        $("#dropDownButton8").jqxDropDownButton({width: '100%', height: 40});
        $("#dropDownButton8").jqxDropDownButton('setContent', 'Select Border Color');
    });
    /*Select*/
    $('select').each(function () {
        var $this = $(this),
                numberOfOptions = $(this).children('option').length;
        $this.addClass('s-hidden');
        $this.wrap('<div class="select"></div>');
        $this.after('<div class="styledSelect"></div>');
        var $styledSelect = $this.next('div.styledSelect');
        $styledSelect.text($this.children('option').eq(0).text());
        var $list = $('<ul />', {
            'class': 'options'
        }).insertAfter($styledSelect);
        for (var i = 0; i < numberOfOptions; i++) {
            $('<li />', {
                text: $this.children('option').eq(i).text(),
                rel: $this.children('option').eq(i).val()
            }).appendTo($list);
        }
        var $listItems = $list.children('li');
        $styledSelect.click(function (e) {
            e.stopPropagation();
            $('div.styledSelect.active').each(function () {
                $(this).removeClass('active').next('ul.options').hide();
            });
            $(this).toggleClass('active').next('ul.options').toggle();
        });
        $listItems.click(function (e) {
            e.stopPropagation();
            $styledSelect.text($(this).text()).removeClass('active');
            $this.val($(this).attr('href'));
            $list.hide();
        });
        $(document).click(function () {
            $styledSelect.removeClass('active');
            $list.hide();
        });
    });
</script>

