
<div class="header-bg">
    <div class="header-title">AGENTS</div>
</div>
<div class="side-menu show-for-small-only">
    <ul>
        <li class="active stats"><a href="<?= $this->basePath('manager'); ?>" title="">Stats</a></li>
        <li class="curr-chat"><a href="<?= $this->basePath('manager/allChat'); ?>" title="">Current Chats</a></li>
        <li class="agent-setup"><a href="<?= $this->basePath('manager/agentSetup'); ?>" title="">Agent Setup</a></li>
        <li class="chat-setup"><a href="<?= $this->basePath('manager/chatSetup'); ?>" title="">Chat Setup</a></li>
        <li class="chat-design"><a href="<?= $this->basePath('manager/chatDesign'); ?>" title="">Chat Design</a></li>
        <li class="report"><a href="javascript:void(0)" title="">Reports</a></li>
        <li class="account"><a href="<?= $this->basePath('manager/accountSettings'); ?>" title="">Accounts</a></li>
    </ul>
</div>
<div class="main-content">           
    <div class="form-group m-t-30 m-b-30"> <a href="#" title="" class="button round"><i class="fi-arrow-left"></i> back</a> </div>
    <div class="tabs-content"><div class="tab-agent-detail p-b-20">
            <div class="tab-agent-header">
                <div class="large-6 columns">
                    <div><span>Customer Name</span> :  James</div>
                    <div><span>Customer Email</span> :  Not Entered</div>
                    <div><span>Page on Site</span> :  http://www.companypage.com/pagecustomeronwhenchatinitiated/...</div>
                </div>
                <div class="large-6 columns">
                    <div>Initiated Chat (or reply to proactive chat)</div>
                    <div>Customer is using SMS (vs Chat on Site, or Chat on Mobile Site?</div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="tab-agent-content">
                <div class="tab-agent-comment">
                    <div class="small-12 columns comment-box p-0 m-b-10">
                        <div class="small-3 large-2 columns l-name">Robert</div>
                        <div class="small-9 large-8 columns comments r-arrow">Hello, I need help with XYZ</div>
                        <div class="large-2 columns hide-for-small-only r-name">&nbsp;</div>
                    </div>
                    <div class="small-12 columns comment-box p-0 m-b-10">
                        <div class="large-2 columns hide-for-small-only l-name">&nbsp;</div>
                        <div class="small-9 large-8 columns comments l-arrow">I will be happy to help you with XYZ, What is your questions?</div>
                        <div class="small-3 large-2 columns r-name">James</div>
                    </div>
                    <div class="small-12 columns comment-box p-0 m-b-10">
                        <div class="small-3 large-2 columns l-name">Robert</div>
                        <div class="small-9 large-8 columns comments r-arrow">I’d like to know the dimensions, so it will fit</div>
                        <div class=" large-2 columns hide-for-small-only r-name">&nbsp;</div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>

        </div>
    </div>        

</div>

<footer>
    <div class="row">		
        <div class="large-12 small-12 columns footer-text">
            Copyright 2016 <a href="<?= $this->url('home') ?>" title="ConnectWithMe" target="_blank">ConnectWithMe.com</a>   •   All Rights Reserved
        </div>
    </div>
</footer>

<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/foundation.min.js'); ?>"></script>
<script src="http://foundation.zurb.com/sites/docs/v/5.5.3/assets/js/modernizr.js"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcore.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxswitchbutton.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdata.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxbuttons.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxscrollbar.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxmenu.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.sort.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.filter.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.selection.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxpanel.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcheckbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxlistbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdropdownlist.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.pager.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/demos.js'); ?>"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var url = "../data/agent-details.xml";
        // prepare the data
        var source =
                {
                    datatype: "xml",
                    datafields: [
                        {name: 'CustomerName', },
                        {name: 'CustomersEmail', },
                        {name: 'ContactDetails', },
                        {name: 'DateTime', },
                        {name: 'ChatDuration', },
                        {name: 'View', }
                    ],
                    root: "entry",
                    record: "content",
                    id: 'AgentID',
                    url: url,
                    //sortcolumn: 'AgentName',
                    //sortdirection: 'asc'
                };
        var dataAdapter = new $.jqx.dataAdapter(source);

        // create jqxgrid.
        $("#jqxgrid").jqxGrid({
            width: '100%',
            //height: 450,
            autoheight: true,
            //autorowheight:true,
            columnsheight: 50,
            rowsheight: 50,
            pagerheight: 50,
            source: dataAdapter,
            sortable: true,
            pageable: true,
            showsortcolumnbackground: false,
            filterable: true,
            altrows: true,
            columns: [
                {text: 'Customer Name', columngroup: 'agentDetails', datafield: 'CustomerName', width: '20%'},
                {text: 'Customer’s Email ID', columngroup: 'agentDetails', datafield: 'CustomersEmail', width: '22%'},
                {text: 'Contact Details', columngroup: 'agentDetails', datafield: 'ContactDetails', width: '22%'},
                {text: 'Date &amp; Time', columngroup: 'agentDetails', datafield: 'DateTime', width: '15%', cellsalign: 'center'},
                {text: 'Chat Duration', columngroup: 'agentDetails', datafield: 'ChatDuration', width: '15%', cellsalign: 'center'},
                {text: 'View', columngroup: 'agentDetails', datafield: 'View', width: '6%', cellsalign: 'center'}
            ],
            columngroups: [
                {text: 'Completed Chat   -  Robert Davis', name: 'agentDetails'}
            ]
        });
    });
</script>