
<div class="header-bg">
    <div class="header-title">HELP LINK   /   FAQ BY DEPARTMENT</div>
</div>
<div class="side-menu show-for-small-only">
    <ul>
        <li class="stats"><a href="<?= $this->basePath('manager'); ?>" title="">Stats</a></li>
        <li class="curr-chat"><a href="<?= $this->basePath('manager/allChat'); ?>" title="">Current Chats</a></li>
        <li class="agent-setup"><a href="<?= $this->basePath('manager/agentSetup'); ?>" title="">Agent Setup</a></li>
        <li class="active chat-setup"><a href="<?= $this->basePath('manager/chatSetup'); ?>" title="">Chat Setup</a></li>
        <li class="chat-design"><a href="<?= $this->basePath('manager/chatDesign'); ?>" title="">Chat Design</a></li>
        <li class="report"><a href="javascript:void(0)" title="">Reports</a></li>
        <li class="account"><a href="<?= $this->basePath('manager/accountSettings'); ?>" title="">Accounts</a></li>
    </ul>
</div>
<div class="main-content">           

    <div class='default'>
        <div id='jqxWidget'>
            <div id="jqxgrid">
            </div>                        
        </div>
    </div>    
    <div class="subtitle">Proactive Chat Campaigns</div>
    <div class='default'>    
        <div id='jqxWidget1'>
            <div id="jqxgrid1">
            </div>                        
        </div>
    </div>

</div>

<footer>
    <div class="row">		
        <div class="large-12 small-12 columns footer-text">
            Copyright 2016 <a href="<?= $this->url('home') ?>" title="ConnectWithMe" target="_blank">ConnectWithMe.com</a>   •   All Rights Reserved
        </div>
    </div>
</footer>

<script type="text/javascript" src="<?= $this->basePath('js/jquery-1.12.3.min.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/foundation.min.js'); ?>"></script>
<script src="http://foundation.zurb.com/sites/docs/v/5.5.3/assets/js/modernizr.js"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcore.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxswitchbutton.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdata.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxbuttons.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxscrollbar.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxmenu.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.sort.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.filter.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.selection.js'); ?>"></script> 
<script type="text/javascript" src="<?= $this->basePath('js/jqxpanel.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxcheckbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxlistbox.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxdropdownlist.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/jqxgrid.pager.js'); ?>"></script>
<script type="text/javascript" src="<?= $this->basePath('js/demos.js'); ?>"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var url = "../data/department.xml";
        // prepare the data
        var source =
                {
                    datatype: "xml",
                    datafields: [
                        {name: 'Department', },
                        {name: 'URL', },
                        {name: 'EditDelete', },
                    ],
                    root: "entry",
                    record: "content",
                    id: 'AgentID',
                    url: url,
                };
        var dataAdapter = new $.jqx.dataAdapter(source);

        // create jqxgrid.
        $("#jqxgrid").jqxGrid({
            width: '100%',
            //height: 450,
            autoheight: true,
            //autorowheight:true,
            columnsheight: 50,
            rowsheight: 50,
            showeverpresentrow: true,
            everpresentrowposition: "bottom",
            pagerheight: 50,
            source: dataAdapter,
            sortable: true,
            pageable: true,
            showsortcolumnbackground: false,
            filterable: true,
            altrows: true,
            columns: [
                {text: 'Department', datafield: 'Department', width: '35%'},
                {text: 'URL’s', datafield: 'URL', width: '55%'},
                {text: 'Edit / Delete', datafield: 'EditDelete', width: '10%', cellsalign: 'center'/* , cellclassname: cellclass , cellsrenderer : ProStatus*/}
            ]
        });

        /**/
        var url = "../data/campaign.xml";
        // prepare the data
        var source =
                {
                    datatype: "xml",
                    datafields: [
                        {name: 'Campaign', },
                        {name: 'URL', },
                        {name: 'ActionRequired', },
                        {name: 'ChatText', },
                        {name: 'EditDelete', },
                    ],
                    root: "entry",
                    record: "content",
                    id: 'AgentID',
                    url: url,
                };
        var dataAdapter = new $.jqx.dataAdapter(source);

        // create jqxgrid.
        $("#jqxgrid1").jqxGrid({
            width: '100%',
            //height: 450,
            autoheight: true,
            //autorowheight:true,
            columnsheight: 50,
            rowsheight: 50,
            showeverpresentrow: true,
            everpresentrowposition: "bottom",
            pagerheight: 50,
            source: dataAdapter,
            sortable: true,
            pageable: true,
            showsortcolumnbackground: false,
            filterable: true,
            altrows: true,
            columns: [
                {text: 'Campaign', datafield: 'Campaign', width: '20%'},
                {text: 'URL’s', datafield: 'URL', width: '30%'},
                {text: 'Action Required', datafield: 'ActionRequired', width: '20%'},
                {text: 'Chat Text', datafield: 'ChatText', width: '20%'},
                {text: 'Edit / Delete', datafield: 'EditDelete', width: '10%', cellsalign: 'center'/* , cellclassname: cellclass , cellsrenderer : ProStatus*/}
            ]
        });

    });
</script>
