<div class="chat-box">
	<div class="step-1 <?= $data->button_dimension ?>">
            <div class="bubbel-btn">Hi there! Thanks for dropping by. Can I help you in any way ? <a class="close-btn" onClick="close_step()" href="javascript:void(0)"><i class="fa fa-close"></i></a></div>
            <a href="javascript:void(0)" onClick="step_one()" title="" class="button radius text-normal">
                <?php if($data->button_text == '') { ?>
                Talk to Me... :) 
                <?php } else {
                    echo $data->button_text;
                } ?>
                <img src="images/chat.png" alt="" title="" class="m-l-20"></a></div>
	<div class="step-3">
    	<div class="chat-box-type-1">
        	<div class="chat-box-type-1-header">
            	<div class="large-6 medium-6 small-6 columns">Connect with Me</div>
                <div class="large-6 medium-6 small-6 columns text-right">Agents Online <img src="images/online-yes.png" class="p-l-5" alt="" title=""></div>
                <div class="clearfix"></div>
            </div>
            <div class="chat-box-type-1-content">
            	<div class="small-12 columns comment-box p-0 m-b-10">
                	<div class="small-3 columns l-name">&nbsp;</div>
                    <div class="small-6 columns comments r-arrow">Hello, I need help with XYZ</div>
                    <div class="small-3 columns r-name">Robert</div>
                </div>                
            	<div class="small-12 columns"><div class="alert alert-box alert-radius">You are in queue. Your queue no, is <span>&ldquo;3&rdquo;</span></div></div>
                <div class="clearfix"></div>
            </div>
            <div class="chat-box-type-1-footer">
            	<form class="">
                    <div class="large-12 columns">
                    	<input class="form-control radius pull-left" type="text">
                        <a class="button radius small v-middle m-r-10" onClick="step_four()">Send</a>
                        <a href="javascript:void(0)" onClick="step_five()"><img src="images/phone.png" alt="" title=""></a>
                    </div>
                </form>
                <div class="clearfix"></div>
            </div>
        </div>
	</div>
    <div class="step-4">
    	<div class="chat-box-type-1">
        	<div class="chat-box-type-2-header">
            	<div class="large-3 medium-3 small-3 columns"><figure class="image-circle"><img src="images/agent.jpg" alt="" title=""></figure></div>
                <div class="large-9 medium-9 small-9 columns agent-details">
                	<div><span>Agents</span> :  James</div>
                    <div><span>Department</span> :  Customer Service</div>
                    <div><span>Page on Site</span> :  Title of the page customer was on</div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="chat-box-type-1-content p-t-20 p-b-20">
            	<div class="small-12 columns comment-box p-0 m-b-10">
                	<div class="small-3 columns l-name">&nbsp;</div>
                    <div class="small-6 columns comments r-arrow">Hello, I need help with XYZ</div>
                    <div class="small-3 columns r-name">Robert</div>
                </div>
                <div class="small-12 columns comment-box p-0 m-b-10">
                	<div class="small-3 columns l-name">James</div>
                    <div class="small-6 columns comments l-arrow">I will be happy to help you with XYZ, What is your questions?</div>
                    <div class="small-3 columns r-name">&nbsp;</div>
                </div>
                <div class="small-12 columns comment-box p-0 m-b-10">
                	<div class="small-3 columns l-name">&nbsp;</div>
                    <div class="small-6 columns comments r-arrow">I’d like to know the dimensions, so it will fit</div>
                    <div class="small-3 columns r-name">Robert</div>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="chat-box-type-1-footer">
            	<form class="">
                    <div class="small-12 columns">
                    	<input class="form-control radius pull-left" type="text">
                        <a class="button radius small v-middle m-r-10">Send</a>
                        <a href="javascript:void(0)" onClick="step_five()"><img src="images/phone.png" alt="" title=""></a>
                    </div>
                </form>
                <div class="clearfix"></div>
            </div>
        </div>
	</div>
    
</div>
<!--<script src="js/jquery-1.12.3.min.js"></script> -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>


<script>
	var level = document.location.search.replace(/\?/,'') || 0;
	$('#nested').attr('href','frame.nested.html?'+(++level));
</script>

<script>
	var iFrameResizer = {
			messageCallback: function(message){
				alert(message,parentIFrame.getId());
			}
		}
</script>

<script type="text/javascript" src="<?= $this->basePath('js/iframeResizer.contentWindow.js') ?>" defer></script>

<script src="<?= $this->basePath('js/foundation.min.js') ?>"></script>
<script type="text/javascript">
$('.step-2').hide();
$('.step-3').hide();
$('.step-4').hide();
$('.step-5').hide();
function step_one(){
	$('.step-1').hide();
	$('.step-3').show();
}
/*function step_two(){
	$('.step-2').hide();
	$('.step-3').show();
}*/
function step_four(){
	$('.step-4').show();
	$('.step-3').hide();
	}
/*function step_five(){
	$('.step-5').show();
	$('.step-3').hide();
	$('.step-4').hide();
}*/
function back_step(){
	$('.step-5').hide();
	$('.step-4').show();	
}
function close_step(){
	$('.bubbel-btn').hide();
}
</script>
