<?php
$email = $form->get('email');
$email->setAttribute('class', 'form-control login-icon');
$email->setAttribute('placeholder', 'Email');

// This provides CSS classes for the submit button:
$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');
?>
<body class="login-bg">
<div class="row login-box">
	<div class="large-12 columns logo"> <a href="<?= $this->url('home') ?>" title="Connect with Me"><img src="<?= $this->basePath('images/logo.png') ?>" alt="Connect with Me" title="Connect with Me"></a> </div>
	<div class="large-12 columns title-text p-20">Forgot Password</div>
	<div class="large-12 p-0">
		 <?php 
		$form->setAttribute('action', $this->url('forgotpassword', ['action' => 'checkemail']));
                $form->setAttribute('class','larger-12');
                $form->prepare();
                echo $this->form()->openTag($form);?>
			<div class="large-12 columns">
				<div class="form-group form-group-box m-t-20">
					<?= $this->formElement($email) ?>
                                        <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
				</div>
			</div>
			<div class="large-12 columns">
                                <div class="form-group cennter m-t-30"> 
                                    <?php echo $this->formSubmit($submit);
                                    echo $this->formHidden($form->get('id'));?>
                                    <!--<a href="#" title="" class="btn btn-default">Register</a> </div>-->
                                </div>
                        </div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script src="<?= $this->basePath('js/foundation.min.js') ?>"></script>
</body>

