<?php

$email = $form->get('email');

$password = $form->get('password');
$password->setAttribute('class', 'form-control passcode-icon');
$password->setAttribute('placeholder', 'Password');

$confirm_password = $form->get('confirm_password');
$confirm_password->setAttribute('class', 'form-control passcode-icon');
$confirm_password->setAttribute('placeholder', 'Confirm Password');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-default');

?>
<body class="login-bg">
<div class="row login-box">
	<div class="large-12 columns logo"> <a href="<?= $this->url('home')  ?>" title="Connect with Me"><img src="<?= $this->basepath('images/logo.png') ?>" alt="Connect with Me" title="Connect with Me"></a> </div>
	<div class="large-12 columns title-text p-20">Reset Your Password</div>
	<div class="large-12 p-0">
		<?php 
		$form->setAttribute('action', $this->url('forgotpassword', ['action' => 'resetpassword']));
                $form->setAttribute('class','larger-12');
                $form->prepare();
                echo $this->form()->openTag($form);
?>
			<div class="large-12 columns">
				<div class="form-group form-group-box m-t-20">
					<?=  $this->formElement($password) ?>
                                        <?=  $this->formElement($email) ?>
                                        <?=  $this->formElementErrors()->render($password, ['class' => 'help-block']) ?>
				</div>
			</div>
			<div class="large-12 columns">
				<div class="form-group form-group-box m-t-20">
					<?=  $this->formElement($confirm_password) ?>
                                        <?=  $this->formElementErrors()->render($confirm_password, ['class' => 'help-block']) ?>
				</div>
			</div>
			<div class="large-12 columns">
				<div class="form-group cennter m-t-30"> 
                                    <?php echo $this->formSubmit($submit); ?>
                                </div>
			</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
</div>
<script src="<?= $this->basepath('js/foundation.min.js') ?>"></script>
</body>
